add Fluent/Chain of Invocations and Loadable Page/Component feature_l…
Ladauser/SauceDemo pull request #2
Opened 2021-11-04 13:23 UTC by Ladauser

…esson10

2021-11-10 17:18 UTC, vchesnakoutest requested changes

2021-11-10 17:18 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    private static final By ERROR_MESSAGE = By.xpath("//*[@id=\"login_button_container\"]/div/form/div[3]");
в локаторе желательно обходиться без /div/form/div[3]. Лучше привязываться к тексту например.

2021-11-10 17:18 UTC, vchesnakoutest commented on src/main/java/pages/ProductsPage.java
> +            public boolean isProductDisplayedInCart(String productName) {
отступ съехал немного

2021-11-10 17:18 UTC, vchesnakoutest commented on src/test/java/tests/CartTests.java
>          Assert.assertEquals(("https://www.saucedemo.com/checkout-step-two.html"),
первым параметром должен идти Актуальный результат (с UI),  а вторым Ожидаемый.

2021-11-11 09:04 UTC, Ladauser commented on src/main/java/pages/LoginPage.java
> +    private static final By ERROR_MESSAGE = By.xpath("//*[@id=\"login_button_container\"]/div/form/div[3]");
исправила

2021-11-11 09:06 UTC, Ladauser commented on src/test/java/tests/CartTests.java
>          Assert.assertEquals(("https://www.saucedemo.com/checkout-step-two.html"),
исправила

2021-11-11 09:06 UTC, Ladauser commented on src/main/java/pages/ProductsPage.java
> +            public boolean isProductDisplayedInCart(String productName) {
исправила

2021-11-11 09:11 UTC, merged